### ISSUE TITLE
AttributeError: 'ClustersOperations' object has no attribute 'create'

### ISSUE THREAD

**Issue by surendrababuguram** [Azure-Samples/hdinsight-python-sdk-samples#4]
Starting to create HDInsight Hadoop cluster hdisamplecluster5305 with Azure Data Lake Storage Gen2
Traceback (most recent call last):
  File "C:\Users\Surendra Babu G\OneDrive - Nuvepro Technologies Private Limited\Desktop\Azure\hdinsight-python-sdk-samples\samples\create_hadoop_cluster_with_adls_gen2_sample.py", line 87, in <module>
    main()
  File "C:\Users\Surendra Babu G\OneDrive - Nuvepro Technologies Private Limited\Desktop\Azure\hdinsight-python-sdk-samples\samples\create_hadoop_cluster_with_adls_gen2_sample.py", line 83, in main
    client.clusters.create(RESOURCE_GROUP_NAME, CLUSTER_NAME, create_params)
AttributeError: 'ClustersOperations' object has no attribute 'create'

**Comment by riteshpallod** [comment]
the examples aren't updated in a while. also there is no version mentioned. I can see that `create` has been replaced with `begin_create`

https://docs.microsoft.com/en-us/python/api/azure-mgmt-hdinsight/azure.mgmt.hdinsight.operations.clustersoperations?view=azure-python
